<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKtD8QtP\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKtD8QtP/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerKtD8QtP.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerKtD8QtP\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerKtD8QtP\App_KernelProdContainer([
    'container.build_hash' => 'KtD8QtP',
    'container.build_id' => 'c179de0d',
    'container.build_time' => 1741615669,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKtD8QtP');
