<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU2qVu9D\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU2qVu9D/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerU2qVu9D.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerU2qVu9D\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerU2qVu9D\App_KernelProdContainer([
    'container.build_hash' => 'U2qVu9D',
    'container.build_id' => '5901473b',
    'container.build_time' => 1788356117,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU2qVu9D');
