<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6OaxGG7\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6OaxGG7/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/Container6OaxGG7.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\Container6OaxGG7\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \Container6OaxGG7\App_KernelProdDebugContainer([
    'container.build_hash' => '6OaxGG7',
    'container.build_id' => 'c9955583',
    'container.build_time' => 1741204482,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6OaxGG7');
