<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO3hR5Cr\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO3hR5Cr/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerO3hR5Cr.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerO3hR5Cr\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerO3hR5Cr\App_KernelProdContainer([
    'container.build_hash' => 'O3hR5Cr',
    'container.build_id' => 'cc178cde',
    'container.build_time' => 1741125531,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO3hR5Cr');
