<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'about' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], [], []],
    'default' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'change_language' => [['language'], ['_controller' => 'App\\Controller\\LanguageController::changeLanguage'], [], [['variable', '/', '[^/]++', 'language', true], ['text', '/change-language']], [], [], []],
    'project_chess' => [[], ['_controller' => 'App\\Controller\\ProjectsController::chess'], [], [['text', '/projects/chess']], [], [], []],
    'project_phase10' => [[], ['_controller' => 'App\\Controller\\ProjectsController::phase10'], [], [['text', '/projects/phase10']], [], [], []],
    'project_interactive_book' => [[], ['_controller' => 'App\\Controller\\ProjectsController::interactiveBook'], [], [['text', '/projects/interactive-book']], [], [], []],
    'project_spotify' => [[], ['_controller' => 'App\\Controller\\ProjectsController::spotify'], [], [['text', '/projects/spotify']], [], [], []],
    'project_aloas' => [[], ['_controller' => 'App\\Controller\\ProjectsController::aloas'], [], [['text', '/projects/aloas']], [], [], []],
    'App\Controller\AboutController::index' => [[], ['_controller' => 'App\\Controller\\AboutController::index'], [], [['text', '/about']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\LanguageController::changeLanguage' => [['language'], ['_controller' => 'App\\Controller\\LanguageController::changeLanguage'], [], [['variable', '/', '[^/]++', 'language', true], ['text', '/change-language']], [], [], []],
    'App\Controller\ProjectsController::chess' => [[], ['_controller' => 'App\\Controller\\ProjectsController::chess'], [], [['text', '/projects/chess']], [], [], []],
    'App\Controller\ProjectsController::phase10' => [[], ['_controller' => 'App\\Controller\\ProjectsController::phase10'], [], [['text', '/projects/phase10']], [], [], []],
    'App\Controller\ProjectsController::interactiveBook' => [[], ['_controller' => 'App\\Controller\\ProjectsController::interactiveBook'], [], [['text', '/projects/interactive-book']], [], [], []],
    'App\Controller\ProjectsController::spotify' => [[], ['_controller' => 'App\\Controller\\ProjectsController::spotify'], [], [['text', '/projects/spotify']], [], [], []],
    'App\Controller\ProjectsController::aloas' => [[], ['_controller' => 'App\\Controller\\ProjectsController::aloas'], [], [['text', '/projects/aloas']], [], [], []],
];
