<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYvKXLd8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYvKXLd8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYvKXLd8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYvKXLd8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYvKXLd8\App_KernelDevDebugContainer([
    'container.build_hash' => 'YvKXLd8',
    'container.build_id' => '65f85192',
    'container.build_time' => 1741199186,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYvKXLd8');
