<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGoSiIaI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGoSiIaI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGoSiIaI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGoSiIaI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGoSiIaI\App_KernelDevDebugContainer([
    'container.build_hash' => 'GoSiIaI',
    'container.build_id' => 'f6038ac0',
    'container.build_time' => 1741127093,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGoSiIaI');
