<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQyirCRn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQyirCRn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQyirCRn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQyirCRn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQyirCRn\App_KernelDevDebugContainer([
    'container.build_hash' => 'QyirCRn',
    'container.build_id' => '1c7d019a',
    'container.build_time' => 1741203829,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQyirCRn');
