<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX0q6IB2\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX0q6IB2/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerX0q6IB2.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerX0q6IB2\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerX0q6IB2\App_KernelProdContainer([
    'container.build_hash' => 'X0q6IB2',
    'container.build_id' => 'd7bad6f6',
    'container.build_time' => 1789031178,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX0q6IB2');
